### ISSUE TITLE
keep 5' and 3' gaps in vp1 run? 

### ISSUE THREAD

**Issue by rneher** [enterovirus-phylo/echo30-2019#1]
The ancestral reconstruction rule has the flag `--keep-overhangs`. This results in "spurious" diversity in the entropy plot. What would be lost of the flag got removed?

![image](https://user-images.githubusercontent.com/8379168/71310886-edc34080-2419-11ea-9170-6764cdd543bb.png)

**Comment by emmahodcroft** [comment]
This would mean that these bases, which are unknown, would be inferred from the ancestral/surrounding sequences. Given how much of some sequences is unknown, we probably shouldn't infer so much. However, these gaps should probably be replaced with 'N's to avoid them showing up in the entropy plot. I will look into this.

**Comment by emmahodcroft** [comment]
So these gaps are added by the aligner - I can try using the flag `--fill-gaps` to prevent this.

**Comment by emmahodcroft** [comment]
The combination of flags `--keep-overhangs` and `--keep-ambiguous` allows the gaps at the end of the sequences (added by the aligner) to be converted to Ns but remain as Ns (state not inferred). These missing ends then end up being translated to `X` which is not counted/included in the entropy plot - so it looks much cleaner. Thanks for pointing this out @rneher ! 
![image](https://user-images.githubusercontent.com/14290674/72424879-f7c13080-3786-11ea-8387-519d35f2a080.png)

**Comment by emmahodcroft** [comment]
Just as a note for future - changing these flags seems to significantly increase tree file size (assume something to do with mutations being recorded). Can bring this down below GitHub limits by removing indents from the tree file.
